server:
  port: 2000 # 端口
  ssl:
    key-store: "xxx"
    key-store-type: PKCS12
    key-store-password: "xxx"
    enabled: false # 启用ssl

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://inquisition-mysql:3306/inquisition?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    enable: false # 启用邮件发送
    host: smtp.qq.com # 邮件服务器地址
    port: 465 # 邮件服务器端口
    protocol: smtps # 邮件协议
    username: "xxx@qq.com" # 邮件发送者账号
    password: "xxx" # 邮件发送者密码 (部分邮箱如QQ邮箱使用授权码)
    from: "xxx@qq.com" # 邮件发送者邮箱
    to: "xxx@qq.com" # 邮件接收者邮箱
  output:
    ansi:
      enabled: always

mybatis:
  table:
    auto: update
    # create	    系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
    # update	    系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
    # none 		系统不做任何处理。
    # add		新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除
  model:
    pack: moe.dazecake.inquisition.model.entity
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# wxpusher配置
wx-pusher:
  enable: false
  app-token: AT_XXXXX

# 存储配置
storage:
# 腾讯云COS 用于存储日志截图 需要自行配置删除规则
  oss:
    enable: false
    secretId: xxxx
    secretKey: xxxx
    bucket: xxx-xxx
    region: xxx
# CHFS——http://iscute.cn/chfs   (开发时CHFS版本为2.0)
# uploadDir是CHFS内的相对位置，直接放在主目录下请留空不填(连“/”也不要留)
  chfs:
      enable: false
      url: http://chfsurl:port
      username: name
      password: yourpassword
      uploadDir: /inquisition/log/img

inquisition:
  secret: xxx # 用于加密token 建议使用系统随机生成的